<?php require_once('../common-sections/app.php'); ?>
<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0">
<meta name="robots" content="noindex,nofollow"><title>Cookie Policy | Velmora Bank</title><meta name="description" content="How Velmora uses essential authentication, preference and service cookies.">
<link rel="icon" type="image/png" href="/assets/images/branding/velmora/icon.png"><link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&family=Manrope:wght@500;600;700;800&display=swap"><link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Rounded:opsz,wght,FILL,GRAD@20..48,300..600,0..1,-50..200"><link rel="stylesheet" href="/assets/stylesheets/public-v2.css?v=<?php echo time(); ?>"></head><body>
<?php include('../common-sections/public-v2-header.php'); ?><main>
<section class="pv2-page-hero"><div class="pv2-container"><span class="pv2-eyebrow">COOKIE POLICY</span><h1 style="max-width:850px">How cookies support secure access and website services.</h1><p style="max-width:760px">Velmora uses essential browser storage for authenticated sessions, optional sign-in persistence and selected site preferences.</p></div></section>
<section class="pv2-section"><div class="pv2-container pv2-legal">
<div class="pv2-policy-meta"><span>Cookie information</span><span>Last updated <?php echo date('F Y'); ?></span></div>
<h2>Essential authentication</h2><p>Online banking uses a secure server-side session identified by an HttpOnly session cookie. The cookie does not contain the customer’s email address as the authentication credential.</p>
<h2>Keep me signed in</h2><p>If you choose “Keep me signed in,” Velmora stores an opaque remember-token cookie. The corresponding token is stored on the server in hashed form and can be revoked when you sign out, change or reset your password, or when account access is restricted.</p>
<h2>Preferences</h2><p>The site may use cookies or browser storage to remember selected preferences, such as whether a notice has been acknowledged. Account preferences are primarily maintained in the application database.</p>
<h2>Live chat and external resources</h2><p>Velmora may use third-party services such as live chat and externally hosted web fonts. Those providers may receive standard browser request information and may use their own cookies or storage in accordance with their policies.</p>
<h2>Your choices</h2><p>You can control cookies through your browser settings. Blocking essential authentication cookies will prevent online banking sign-in or may cause an authenticated session to end.</p>
<h2>Questions</h2><p>For questions about cookie use or privacy, contact <a href="/contact/" style="color:#315978;font-weight:700">Velmora Support</a>.</p>
</div></section></main><?php include('../common-sections/public-v2-footer.php'); ?></body></html>