<?php require_once('../common-sections/app.php'); ?>
<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0">
<meta name="robots" content="noindex,nofollow"><title>Documents & Forms | Velmora Bank</title><meta name="description" content="Velmora Bank policies, security guidance and support for account-service documents.">
<link rel="icon" type="image/png" href="/assets/images/branding/velmora/icon.png"><link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&family=Manrope:wght@500;600;700;800&display=swap"><link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Rounded:opsz,wght,FILL,GRAD@20..48,300..600,0..1,-50..200"><link rel="stylesheet" href="/assets/stylesheets/public-v2.css?v=<?php echo time(); ?>"></head><body>
<?php include('../common-sections/public-v2-header.php'); ?><main>
<section class="pv2-page-hero"><div class="pv2-container"><span class="pv2-eyebrow">DOCUMENTS &amp; FORMS</span><h1 style="max-width:850px">Policies, guidance and account-service documents in one place.</h1><p style="max-width:760px">Use the links below for published website policies and security guidance. Where a banking request requires a specific form or supporting document, Velmora Support can provide the appropriate instructions.</p></div></section>
<section class="pv2-section pv2-soft"><div class="pv2-container"><div class="pv2-doc-grid">
<article class="pv2-doc"><span class="material-symbols-rounded">privacy_tip</span><h3>Privacy Policy</h3><p>How personal, account, security and support information is handled.</p><footer><a href="/privacy/">Read privacy policy →</a></footer></article>
<article class="pv2-doc"><span class="material-symbols-rounded">contract</span><h3>Terms of Use</h3><p>Terms for accessing the Velmora website and online banking services.</p><footer><a href="/terms/">Read terms →</a></footer></article>
<article class="pv2-doc"><span class="material-symbols-rounded">cookie</span><h3>Cookie Policy</h3><p>Information about essential authentication, preference and service cookies.</p><footer><a href="/cookie-policy/">Read cookie policy →</a></footer></article>
<article class="pv2-doc"><span class="material-symbols-rounded">security</span><h3>Security guidance</h3><p>How to recognize suspicious contact and protect account access.</p><footer><a href="/security/">Security &amp; Fraud Center →</a></footer></article>
<article class="pv2-doc"><span class="material-symbols-rounded">person_edit</span><h3>Account servicing</h3><p>For profile changes, account instructions or supporting documents, contact support with the relevant account context.</p><footer><a href="/contact/">Contact support →</a></footer></article>
<article class="pv2-doc"><span class="material-symbols-rounded">gavel</span><h3>Disputes &amp; investigations</h3><p>For a transaction dispute or investigation, include the transaction reference and supporting information when contacting Velmora.</p><footer><a href="/support/">Support center →</a></footer></article>
</div></div></section></main><?php include('../common-sections/public-v2-footer.php'); ?></body></html>