<?php require_once('../common-sections/app.php'); ?>
<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0">
<meta name="robots" content="noindex,nofollow"><title>Legal & Disclosures | Velmora Bank</title><meta name="description" content="Velmora Bank privacy, terms, cookie, accessibility, pricing and customer information.">
<link rel="icon" type="image/png" href="/assets/images/branding/velmora/icon.png"><link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&family=Manrope:wght@500;600;700;800&display=swap"><link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Rounded:opsz,wght,FILL,GRAD@20..48,300..600,0..1,-50..200"><link rel="stylesheet" href="/assets/stylesheets/public-v2.css?v=<?php echo time(); ?>"></head><body>
<?php include('../common-sections/public-v2-header.php'); ?><main>
<section class="pv2-page-hero"><div class="pv2-container"><span class="pv2-eyebrow">LEGAL &amp; DISCLOSURES</span><h1 style="max-width:900px">Important information about using Velmora services.</h1><p style="max-width:760px">Review the policies and service information that apply to website access, account security, privacy, cookies and product-specific terms.</p></div></section>
<section class="pv2-section"><div class="pv2-container"><div class="pv2-card-grid">
<article class="pv2-card"><span class="pv2-card-icon"><span class="material-symbols-rounded">privacy_tip</span></span><h3>Privacy Policy</h3><p>How information is collected, used, protected and shared in connection with Velmora services.</p><a href="/privacy/">Read privacy policy <span class="material-symbols-rounded">arrow_forward</span></a></article>
<article class="pv2-card"><span class="pv2-card-icon"><span class="material-symbols-rounded">contract</span></span><h3>Terms of Use</h3><p>Rules and responsibilities for accessing the website and online banking environment.</p><a href="/terms/">Read terms <span class="material-symbols-rounded">arrow_forward</span></a></article>
<article class="pv2-card"><span class="pv2-card-icon"><span class="material-symbols-rounded">cookie</span></span><h3>Cookie Policy</h3><p>How essential cookies and related browser storage support authentication and site services.</p><a href="/cookie-policy/">Read cookie policy <span class="material-symbols-rounded">arrow_forward</span></a></article>
<article class="pv2-card"><span class="pv2-card-icon"><span class="material-symbols-rounded">accessibility_new</span></span><h3>Accessibility</h3><p>Velmora’s approach to usable digital banking and how to request assistance.</p><a href="/accessibility/">Read statement <span class="material-symbols-rounded">arrow_forward</span></a></article>
<article class="pv2-card"><span class="pv2-card-icon"><span class="material-symbols-rounded">request_quote</span></span><h3>Rates &amp; Fees</h3><p>How applicable pricing is presented for specific services and transactions.</p><a href="/rates/">View rates &amp; fees <span class="material-symbols-rounded">arrow_forward</span></a></article>
<article class="pv2-card"><span class="pv2-card-icon"><span class="material-symbols-rounded">folder_open</span></span><h3>Documents &amp; Forms</h3><p>Published policies, security guidance and access to account-service documentation.</p><a href="/documents/">View documents <span class="material-symbols-rounded">arrow_forward</span></a></article>
</div></div></section></main><?php include('../common-sections/public-v2-footer.php'); ?></body></html>