<?php require_once('../common-sections/app.php'); ?>
<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0">
<meta name="robots" content="noindex,nofollow"><title>About Velmora | Velmora Bank</title><meta name="description" content="About Velmora Bank and its approach to account access, payments, service and security.">
<link rel="icon" type="image/png" href="/assets/images/branding/velmora/icon.png"><link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&family=Manrope:wght@500;600;700;800&display=swap"><link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Rounded:opsz,wght,FILL,GRAD@20..48,300..600,0..1,-50..200"><link rel="stylesheet" href="/assets/stylesheets/public-v2.css?v=<?php echo time(); ?>"></head><body>
<?php include('../common-sections/public-v2-header.php'); ?><main>
<section class="pv2-page-hero"><div class="pv2-container pv2-hero-grid">
<div><span class="pv2-eyebrow">ABOUT VELMORA</span><h1>Banking organized around clear account information and accountable service.</h1><p>Velmora brings account access, money movement, identity review, security information and customer support into one consistent digital relationship.</p><div class="pv2-actions"><a class="pv2-btn primary" href="/personal/">Personal banking</a><a class="pv2-btn secondary" href="/business/">Business banking</a></div></div>
<div class="pv2-hero-image"><img src="/assets/images/home/hero/bank-exterior.jpg" alt="Velmora banking services"><div class="pv2-image-note"><small>VELMORA</small><strong>Accounts · payments · security · support</strong></div></div>
</div></section>
<section class="pv2-section"><div class="pv2-container">
<div class="pv2-section-head"><div><span class="pv2-eyebrow">OUR APPROACH</span><h2>Make important financial actions easier to understand and review.</h2></div><p>Account information should remain connected to the records and controls that support it.</p></div>
<div class="pv2-card-grid">
<article class="pv2-card"><span class="pv2-card-icon"><span class="material-symbols-rounded">account_balance</span></span><h3>Account clarity</h3><p>Accounts retain their currency, status and transaction history instead of relying on presentation-only balances.</p></article>
<article class="pv2-card"><span class="pv2-card-icon"><span class="material-symbols-rounded">sync_alt</span></span><h3>Traceable money movement</h3><p>Transfers and foreign-exchange activity use references, status and review steps that remain visible in the banking relationship.</p></article>
<article class="pv2-card"><span class="pv2-card-icon"><span class="material-symbols-rounded">shield</span></span><h3>Security controls</h3><p>Authentication, access restrictions, password recovery and recorded security events support account protection.</p></article>
<article class="pv2-card"><span class="pv2-card-icon"><span class="material-symbols-rounded">support_agent</span></span><h3>Human support</h3><p>Customers can move from self-service to direct support when an account, payment or security issue needs attention.</p></article>
</div></div></section>
<section class="pv2-section pv2-soft"><div class="pv2-container pv2-split"><div class="pv2-split-copy"><span class="pv2-eyebrow">THE RELATIONSHIP</span><h2>One customer profile across accounts, identity and support.</h2><p>Online banking connects account records, transaction history, notifications, KYC information, security activity and support cases so customers and authorized staff can work from consistent information.</p></div><div class="pv2-split-image"><img src="/assets/images/home/hero/consulting-banner.jpg" alt="Customer banking support"></div></div></section>
<section class="pv2-cta"><div class="pv2-container"><div><span class="pv2-eyebrow" style="color:#8fa8bf">BANK WITH VELMORA</span><h2>Explore the services available to you.</h2></div><div><a class="pv2-btn gold" href="/signup/">Open an account</a><a class="pv2-btn secondary" href="/contact/">Contact us</a></div></div></section>
</main><?php include('../common-sections/public-v2-footer.php'); ?></body></html>