<?php require_once('../common-sections/app.php'); ?>
<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0">
<meta name="robots" content="noindex,nofollow"><title>Privacy Policy | Velmora Bank</title><meta name="description" content="How Velmora handles website, account, KYC, transaction, security and support information.">
<link rel="icon" type="image/png" href="/assets/images/branding/velmora/icon.png"><link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&family=Manrope:wght@500;600;700;800&display=swap"><link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Rounded:opsz,wght,FILL,GRAD@20..48,300..600,0..1,-50..200"><link rel="stylesheet" href="/assets/stylesheets/public-v2.css?v=<?php echo time(); ?>"></head><body>
<?php include('../common-sections/public-v2-header.php'); ?><main>
<section class="pv2-page-hero"><div class="pv2-container"><span class="pv2-eyebrow">PRIVACY POLICY</span><h1 style="max-width:850px">How information is handled when you use Velmora.</h1><p style="max-width:760px">This policy explains the principal categories of information used to provide accounts, online banking, identity review, support and security services.</p></div></section>
<section class="pv2-section"><div class="pv2-container pv2-legal">
<div class="pv2-policy-meta"><span>Privacy information</span><span>Last updated <?php echo date('F Y'); ?></span></div>
<h2>Information we process</h2><p>Velmora may process information you provide when registering, using an account, completing identity checks or contacting support. This can include name, email address, password hash, contact details, date of birth, residential information, occupation, source-of-income information, account identifiers, transaction information, KYC information, support messages and profile images.</p>
<h3>Account and transaction information</h3><p>Account type, account number, currency, status, transaction history, beneficiaries, transfer details, foreign-exchange activity, references, value dates and related status information may be stored to provide and administer account services.</p>
<h3>Security and device information</h3><p>Velmora may record sign-in time, IP address, browser or device information and security events to protect accounts, investigate suspicious activity and maintain service reliability.</p>
<h2>How information is used</h2><ul><li>To create and administer customer profiles and accounts.</li><li>To provide online banking and display account information.</li><li>To process and record account instructions, transfers and foreign-exchange activity.</li><li>To support identity and KYC workflows.</li><li>To respond to customer and support requests.</li><li>To send account, transaction and security communications.</li><li>To protect the service, investigate misuse and maintain technical reliability.</li></ul>
<h2>Service providers</h2><p>Service providers may process information where required for hosting, database infrastructure, email delivery, customer support, live chat or other operational services. Access should be limited to what is required for the relevant service.</p>
<h2>Retention and security</h2><p>Information is retained for as long as reasonably required for account administration, security, operational, contractual or applicable legal obligations. Velmora uses access controls and other technical measures intended to protect account information, but customers should also protect passwords and devices used to access online banking.</p>
<h2>Your questions or requests</h2><p>For privacy questions or requests concerning your information, contact <a href="/contact/" style="color:#315978;font-weight:700">Velmora Support</a>. Any rights available to you may depend on the law applicable to your circumstances.</p>
</div></section></main><?php include('../common-sections/public-v2-footer.php'); ?></body></html>