<?php
require_once __DIR__ . '/../_app.php';
require_once __DIR__ . '/../_layout.php';
$db=connectToDatabase();
$res=$db->query("SELECT id,transaction_id,type,user_email,account_number,amount,currency,status,time,channel,value_date,posted_at,to_bank_name,recipient_name,counter_currency,counter_amount,fx_rate,archived_previous_status,archived_by,archived_at FROM transactions ORDER BY time DESC,id DESC");
$rows=$res?$res->fetch_all(MYSQLI_ASSOC):[];$db->close();
$success=cpv2TakeFlash('success');$error=cpv2TakeFlash('error');
cpv2Start('Transactions','transactions');
?>
<section class="op-heading"><div><span class="op-kicker">LEDGER</span><h1>Transactions</h1><p>Operational bank record of ledger entries. Archived entries remain fully retained here while being excluded from the customer-visible ledger and customer balance.</p></div></section>
<?php if($success):?><div class="op-alert success"><?php echo htmlspecialchars($success); ?></div><?php endif;?>
<?php if($error):?><div class="op-alert error"><?php echo htmlspecialchars($error); ?></div><?php endif;?>
<section class="op-panel"><div class="op-search"><input id="opSearch" type="search" placeholder="Search reference, email, account or status"></div><div class="op-table-wrap"><table class="op-table" id="opSearchTable"><thead><tr><th>Reference</th><th>Customer</th><th>Type</th><th>Account</th><th>Channel</th><th>Status</th><th>Amount</th><th>Value date</th><th>Archived by</th><th>Archived at</th><th>Action</th></tr></thead><tbody>
<?php foreach($rows as $r): $isArchived=strtolower((string)$r['status'])==='archived'; ?><tr><td><strong><?php echo htmlspecialchars($r['transaction_id']); ?></strong><?php if(!empty($r['recipient_name'])||!empty($r['to_bank_name'])):?><small><?php echo htmlspecialchars(trim(($r['recipient_name']??'').(!empty($r['recipient_name'])&&!empty($r['to_bank_name'])?' · ':'').($r['to_bank_name']??''))); ?></small><?php endif;?></td><td><?php echo htmlspecialchars($r['user_email']); ?></td><td><?php echo htmlspecialchars($r['type']); ?></td><td><?php echo htmlspecialchars($r['account_number']); ?></td><td><?php echo htmlspecialchars($r['channel']?:'Online Banking'); ?></td><td><span class="op-status <?php echo htmlspecialchars(strtolower($r['status'])); ?>"><?php echo htmlspecialchars($r['status']); ?></span><?php if($isArchived&&$r['archived_previous_status']):?><small>Previous: <?php echo htmlspecialchars($r['archived_previous_status']); ?></small><?php endif;?></td><td><?php echo htmlspecialchars(velmoraFormatCurrency((float)$r['amount'],$r['currency'])); ?><?php if(!empty($r['counter_currency'])&&$r['counter_amount']!==null):?><small>Countervalue <?php echo htmlspecialchars(velmoraFormatCurrency((float)$r['counter_amount'],$r['counter_currency'])); ?></small><?php endif;?></td><td><?php echo htmlspecialchars($r['value_date']?:date('Y-m-d',(int)$r['time'])); ?></td><td><?php echo $isArchived?htmlspecialchars((string)$r['archived_by']):'—'; ?></td><td><?php echo $isArchived&&$r['archived_at']?htmlspecialchars(date('M d, Y H:i',strtotime((string)$r['archived_at']))):'—'; ?></td><td>
<?php if(!$isArchived):?><form method="post"><?php echo cpv2CsrfInput(); ?><input type="hidden" name="transaction_row_id" value="<?php echo (int)$r['id']; ?>"><button class="op-btn danger" type="submit" name="cpv2_archive_transaction" value="1" onclick="return confirm('Archive this transaction? It will disappear from customer transaction records and customer balance calculations, but remain in the bank record.')">Archive</button></form><?php else:?><strong>Archived</strong><?php endif;?>
</td></tr><?php endforeach;?>
<?php if(empty($rows)):?><tr><td colspan="11">No transactions found.</td></tr><?php endif;?>
</tbody></table></div></section>
<script>document.getElementById('opSearch')?.addEventListener('input',function(){const q=this.value.toLowerCase();document.querySelectorAll('#opSearchTable tbody tr').forEach(r=>r.style.display=r.textContent.toLowerCase().includes(q)?'':'none')})</script>
<?php cpv2End(); ?>
