<?php require_once('../common-sections/app.php'); ?>
<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0">
<meta name="robots" content="noindex,nofollow"><title>Terms of Use | Velmora Bank</title><meta name="description" content="Terms governing access to the Velmora website and online banking services.">
<link rel="icon" type="image/png" href="/assets/images/branding/velmora/icon.png"><link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&family=Manrope:wght@500;600;700;800&display=swap"><link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Rounded:opsz,wght,FILL,GRAD@20..48,300..600,0..1,-50..200"><link rel="stylesheet" href="/assets/stylesheets/public-v2.css?v=<?php echo time(); ?>"></head><body>
<?php include('../common-sections/public-v2-header.php'); ?><main>
<section class="pv2-page-hero"><div class="pv2-container"><span class="pv2-eyebrow">TERMS OF USE</span><h1 style="max-width:850px">Terms for using the Velmora website and online banking services.</h1><p style="max-width:760px">These terms set expectations for access, credentials, account instructions, service information and acceptable use.</p></div></section>
<section class="pv2-section"><div class="pv2-container pv2-legal">
<div class="pv2-policy-meta"><span>Website &amp; online banking</span><span>Last updated <?php echo date('F Y'); ?></span></div>
<h2>Use of the website</h2><p>You may use Velmora services only for lawful purposes and within the functions made available to you. You must not attempt unauthorized access, interfere with service operation, manipulate records, probe security controls or use another person’s credentials.</p>
<h2>Account credentials</h2><p>You are responsible for protecting your password and devices used for online banking. Notify support promptly if you believe your credentials or account access may have been compromised. Velmora Support should not require you to disclose your full password or one-time security code.</p>
<h2>Account instructions and records</h2><p>Transactions and account instructions may be subject to validation, processing, status changes and review. References, transaction status and other account records shown in online banking should be used when contacting support about a specific instruction.</p>
<h2>Rates, quotes and financing</h2><p>Foreign-exchange quotes may be time-limited. Card, financing and other product terms are subject to the terms presented or confirmed for the applicable service. A request or application does not by itself constitute approval.</p>
<h2>Restricted access</h2><p>Velmora may restrict online access where reasonably required for security, investigation, account protection or service administration. Where appropriate, the customer may be directed to contact support for resolution.</p>
<h2>Availability</h2><p>Velmora may maintain, modify or temporarily suspend website functions. Where a service is unavailable or requires additional review, contact support for assistance.</p>
<h2>Intellectual property</h2><p>Velmora branding, site design, original content and software are protected by applicable intellectual-property rights. Third-party services and materials remain subject to their respective rights and terms.</p>
<h2>Contact</h2><p>Questions about these terms can be sent through <a href="/contact/" style="color:#315978;font-weight:700">Velmora Support</a>.</p>
</div></section></main><?php include('../common-sections/public-v2-footer.php'); ?></body></html>