<?php require_once('../common-sections/app.php'); ?>
<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0">
<meta name="robots" content="noindex,nofollow"><title>Accessibility Statement | Velmora Bank</title><meta name="description" content="Velmora Bank accessibility approach and support contact.">
<link rel="icon" type="image/png" href="/assets/images/branding/velmora/icon.png"><link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&family=Manrope:wght@500;600;700;800&display=swap"><link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Rounded:opsz,wght,FILL,GRAD@20..48,300..600,0..1,-50..200"><link rel="stylesheet" href="/assets/stylesheets/public-v2.css?v=<?php echo time(); ?>"></head><body>
<?php include('../common-sections/public-v2-header.php'); ?><main>
<section class="pv2-page-hero"><div class="pv2-container"><span class="pv2-eyebrow">ACCESSIBILITY</span><h1 style="max-width:850px">Banking information should be usable across devices and access needs.</h1><p style="max-width:760px">Velmora aims to provide clear structure, responsive layouts, understandable forms and keyboard-friendly interaction throughout public and authenticated services.</p></div></section>
<section class="pv2-section"><div class="pv2-container pv2-legal">
<div class="pv2-policy-meta"><span>Accessibility approach</span><span>Last updated <?php echo date('F Y'); ?></span></div>
<h2>Our approach</h2><ul><li>Use semantic headings and consistent information hierarchy.</li><li>Provide labels and instructions for forms and financial workflows.</li><li>Support keyboard operation for interactive controls where practicable.</li><li>Use responsive layouts across desktop, tablet and mobile screens.</li><li>Avoid relying on color alone to communicate important status information.</li><li>Use readable contrast and restrained decorative effects.</li></ul>
<h2>Ongoing improvement</h2><p>Accessibility is reviewed as features and content change. Some combinations of browsers, assistive technologies or legacy components may behave differently, and reported issues are investigated as part of service maintenance.</p>
<h2>Need assistance?</h2><p>If a page or banking task is difficult to access, contact <a href="/contact/" style="color:#315978;font-weight:700">Velmora Support</a> and, if possible, include the page, device, browser or assistive technology involved.</p>
</div></section></main><?php include('../common-sections/public-v2-footer.php'); ?></body></html>